version: "3.9"

services:
  hardhat:
    image: cartesi/rollups-hardhat:0.9.1
    command:
      [
        "node",
        "--network",
        "hardhat",
        "--export",
        "/opt/cartesi/share/deployments/localhost.json",
      ]
    init: true
    ports:
      - "8545:8545"
    healthcheck:
      test:
        ["CMD", "test", "-f", "/opt/cartesi/share/deployments/localhost.json"]
      interval: 30s
      timeout: 30s
      retries: 5
    volumes:
      - blockchain-data:/opt/cartesi/share/deployments
      - ./deployments:/app/rollups/deployments

  hardhat_stop_automine:
    image: curlimages/curl:7.84.0
    restart: on-failure
    depends_on:
      hardhat:
        condition: service_healthy
    command:
      [
        "--data",
        '{"id":1337,"jsonrpc":"2.0","method":"evm_setAutomine","params":[false]}',
        "http://hardhat:8545",
      ]

  hardhat_set_interval:
    image: curlimages/curl:7.84.0
    restart: on-failure
    depends_on:
      hardhat:
        condition: service_healthy
      hardhat_stop_automine:
        condition: service_completed_successfully
    command:
      [
        "--data",
        '{"id":1337,"jsonrpc":"2.0","method":"evm_setIntervalMining","params":[5000]}',
        "http://hardhat:8545",
      ]
volumes:
  blockchain-data: {}
